author: "Nikolas Siccha"
project:
  type: website
website:
  title: "StanBlocks.jl"
  navbar:
    search: true
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Performance"
        href: performance.qmd
      - text: "Implementations"
        href: implementations.qmd
      - icon: github
        href:  https://github.com/nsiccha/StanBlocks.jl
format: 
    html:
        page-layout: full
        toc: true
        include-in-header:
            text: |
                <link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.dataTables.css" />
                <script src="cache/dataTables.js"></script>
                <script>
                  $(document).ready( function () {
                      $('table.interactive').DataTable({paging: false});
                  } );
                </script
jupyter: julia-1.10
execute:
  echo: false
  cache: true
  daemon: 60000
filters:
   - include-code-files
