[deps]
BayesianRegressionModels = "cdd3e328-398d-47a6-a87b-6047aaf4b4bc"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
MutatingFunctions = "8a4c2d94-4b3b-4f9e-be63-a3c0cd816e3a"
OutputSignatures = "86cfaae4-1704-4c69-ba62-d919d81ae5f8"
StanBlocks = "2e771a56-c23a-4e0b-9282-20c2e37157e9"

[sources.BayesianRegressionModels]
url = "https://github.com/JuliaBayes/BayesianRegressionModels.jl"
rev = "ns/devibe"

[sources.MutatingFunctions]
url = "https://github.com/nsiccha/MutatingFunctions.jl"

[sources.OutputSignatures]
url = "https://github.com/nsiccha/OutputSignatures.jl"

[sources.StanBlocks]
path = ".."
